# Generated by Django 6.0.6 on 2026-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.IntegerField(blank=True, choices=[(800, '800'), (900, '900'), (1000, '1000'), (1100, '1100'), (1200, '1200'), (1300, '1300'), (1400, '1400'), (1500, '1500'), (1600, '1600'), (1700, '1700'), (1800, '1800'), (1900, '1900'), (2000, '2000')], null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('nepali_date', models.CharField(help_text='Enter date in Nepali format (e.g., 2080-03-15)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
